export const semana_do_colegio_tests = [
    {
      "id": 981,
      "question_text": "Colabora com o efeito de humor da tira a ideia de que Calvin, o menino,",
      "question_year": 2022,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "É UM ABSURDO PESSOAS DE SEIS ANOS NÃO PODEREM VOTAR! AQUI ESTOU EU, UM CIDADÃO SEM PODER ESCOLHER SEU GOVERNO! VOCÊ ESTÁ PREOCUPADO COM OS RUMOS DO NOSSO PAÍS? NÃO. SÓ QUERIA UM PEDAÇO MAIOR DO BOLO. (Bill W aterson, “O melhor de Calvin”. https://cultura.estadao.com.br , 24.08.2021)",
      "area_id": 1000,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 1,
      "has_image": false,
      "has_latex": false
    },
    {
      "id": 1457,
      "question_text": "ew",
      "question_year": 213,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "ewqeqwe",
      "area_id": 1019,
      "question_creator": "ewq",
      "official_test_name": "ewq",
      "question_number": 132,
      "has_image": true,
      "has_latex": false
    },
    {
      "id": 1234,
      "question_text": "José Manuel é fumante e jurou para si mesmo parar de fumar.\nComo ninguém é de ferro, decidiu fumar os últimos 81 cigarros\nque tinha em casa, um por dia. Entretanto, José Manuel logo\ndescobriu que, unindo três tocos desses cigarros com uma fita\nadesiva, fazia outro cigarro. Dessa forma, sem quebrar seu\njuramento, José Manuel foi repetindo esse processo da união\ndos tocos e abandonou definitivamente o cigarro depois de\n",
      "question_year": 2009,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": " ",
      "area_id": 1019,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 1,
      "has_image": true,
      "has_latex": false
    },
    {
      "id": 1458,
      "question_text": "weewqe",
      "question_year": 32144,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "rweqrweq",
      "area_id": 1019,
      "question_creator": "rwqe",
      "official_test_name": "wqerqwe",
      "question_number": 32142314,
      "has_image": false,
      "has_latex": false
    },
    {
      "id": 1459,
      "question_text": "qwerwqerew",
      "question_year": 42314,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "qrweqr",
      "area_id": 1019,
      "question_creator": "rwqerwqer",
      "official_test_name": "rewqrwqe",
      "question_number": 23,
      "has_image": true,
      "has_latex": false
    },
    {
      "id": 1460,
      "question_text": "1234123",
      "question_year": 1234321,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "42134",
      "area_id": 1019,
      "question_creator": "4321",
      "official_test_name": "41324213",
      "question_number": 41234,
      "has_image": true,
      "has_latex": false
    },
 ]  //mudar dps