export const semana_do_colegio_tests = [
    {
      "id": 981,
      "question_text": "Colabora com o efeito de humor da tira a ideia de que Calvin, o menino,",
      "question_year": 2022,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "É UM ABSURDO PESSOAS DE SEIS ANOS NÃO PODEREM VOTAR! AQUI ESTOU EU, UM CIDADÃO SEM PODER ESCOLHER SEU GOVERNO! VOCÊ ESTÁ PREOCUPADO COM OS RUMOS DO NOSSO PAÍS? NÃO. SÓ QUERIA UM PEDAÇO MAIOR DO BOLO. (Bill W aterson, “O melhor de Calvin”. https://cultura.estadao.com.br , 24.08.2021)",
      "area_id": 1000,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 1,
      "has_image": false,
      "has_latex": false
    },
    {
      "id": 904,
      "question_text": "Em um estudo sobre solo, foi utilizada uma coluna de vidro, com uma torneira adaptada em sua extremidade, conforme ilustração. Em seguida, 100 mL de areia seca foram coloca- dos dentro da coluna. Então, lentamente, foi acrescentado água, até que o nível da água, após preencher os espaços entre os grãos, atingisse a marca de 100 mL. Após medir a quantidade de água colocada na coluna (1), a torneira foi aberta e foi medido o tempo em segundos (2), no qual toda a água presente na coluna demorou para escoar pela torneira. As propriedades do solo que foram medidas em 1 e 2 foram, respectivamente,",
      "question_year": 2020,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "",
      "area_id": 1072,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 31,
      "has_image": false,
      "has_latex": false
    },
    {
      "id": 1234,
      "question_text": "José Manuel é fumante e jurou para si mesmo parar de fumar.\nComo ninguém é de ferro, decidiu fumar os últimos 81 cigarros\nque tinha em casa, um por dia. Entretanto, José Manuel logo\ndescobriu que, unindo três tocos desses cigarros com uma fita\nadesiva, fazia outro cigarro. Dessa forma, sem quebrar seu\njuramento, José Manuel foi repetindo esse processo da união\ndos tocos e abandonou definitivamente o cigarro depois de\n",
      "question_year": 2009,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": " ",
      "area_id": 1019,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 1,
      "has_image": true,
      "has_latex": false
    },
    {
      "id": 734,
      "question_text": "De acordo com o texto, é correto afirmar que",
      "question_year": 2014,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "Celular es japoneses para ter ceira idade começam a ser vendidos na França A porcentagem de pessoas idosas no Japão é a mais alta do mundo, com 23% da população representada por pessoas com mais de 65 anos. De acordo com o censo do Serviço de Estatísti - cas do Japão, estima-se que essa taxa subirá para 39% até 2050. Pensando nesse nicho de mercado em expansão, a empresa japonesa Fujitsu, em parceria com a NTT Docomo, passou a desenvolver aparelhos celulares com tecnologia denominada raku-raku, ou “fáceis de usar”. Ela foi criada para facilitar o uso dos celulares, para que os idosos possam se adaptar às novas tecnologias. Os “raku-raku phones” já são comercializados no Japão há 12 anos e agora chegarão ao continente europeu. A parceria da Fujitsu com a Orange – empresa de telefonia móvel que tem atuação na França e no Reino Unido – já foi anunciada. Desde o lançamento, já foram vendidos mais de 20 milhões de celulares raku-raku no mercado japonês. Os primeiros apa - relhos eram mais simples, porém já comportam uma linha com mais de 15 modelos diferentes, incluindo smartphones. Esses aparelhos têm fontes diferenciadas para facilitar a leitura, microfones duplos que diminuem a produção de ruídos, alto-falantes melhorados para facilitar a escuta, botões maiores e mais sensíveis ao toque, tecnologia para tornar a voz mais clara e lenta a fim de facilitar a compreensão de quem escuta. T odas essas mudanças são pensadas para melhorar a qualidade de vida dos usuários, que se sentirão mais seguros ao usar um celular . (Karin Kimura. http://madeinjapan.uol.com.br/2013/09/13/celulares-japoneses- -para-terceira-idade-comecam-a-ser-vendidos-na-franca/. Adaptado)",
      "area_id": 1000,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 1,
      "has_image": false,
      "has_latex": false
    },
    {
      "id": 1159,
      "question_text": "Entre dois postes, Joãozinho contou 60 pássaros que estavam\ndescansando nos três fios elétricos existentes. De repente, 6\npássaros voaram do primeiro fio, 8 voaram do segundo fio\ne 4 voaram do terceiro fio. Se Joãozinho observou que ficou\no mesmo número de pássaros em cada um dos três fios elétricos, então o número de pássaros que estavam inicialmente\ndescansando no segundo fio era\n",
      "question_year": 2008,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": " ",
      "area_id": 1019,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 4,
      "has_image": false,
      "has_latex": false
    },
    {
     "id": 906,
      "question_text": "A água usada em pias, chuveiros, tanques e máquinas de lavar pode ser reutilizada na limpeza da casa. Como essa água tem muito sabão, detergente, restos de alimentos e gor- dura, ela deve passar por um tratamento que elimine esses materiais. Para isso, pode ser utilizado o “jardim filtrante”, que consiste em um tanque com o fundo impermeabilizado, con- tendo areia e brita na parte inferior e água na parte superior, no qual são cultivadas plantas aquáticas, como o aguapé. O processo é apresentado na ilustração a seguir. (https://agua-sua-linda.tumblr.com/post/159491798163/a-%C3%A1gua- -usada-em-pias-chuveiros-tanques-e. Adaptado) Ao passar pelos recipientes 1 e 2, a água é submetida, res- pectivamente, aos processos de",
      "question_year": 2020,
      "total_answers": 0,
      "total_correct_answers": 0,
      "difficulty": "facil",
      "additional_info": "",
      "area_id": 1072,
      "question_creator": "VUNESP",
      "official_test_name": "CTI",
      "question_number": 33,
      "has_image": false,
      "has_latex": false
    },
 ]  //mudar dps